name: Deploy Backend to Render

on:
    pull_request:
        branches:
            - main
        paths:
            - "backend/**"
            - ".github/workflows/deploy-backend.yml"
            - "Dockerfile"
    push:
        branches:
            - main
        paths:
            - "backend/**"
            - ".github/workflows/deploy-backend.yml"
            - "Dockerfile"

jobs:
    build-and-push:
        # Endast bygga när PR mergas till main
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ secrets.DOCKER_HUB_USERNAME }}/meetup-app-backend
                  tags: |
                      type=ref,event=branch
                      type=sha,prefix={{branch}}-
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./backend
                  file: ./backend/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/meetup-app-backend:buildcache
                  cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/meetup-app-backend:buildcache,mode=max

            - name: Trigger Render deployment
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                  service-id: ${{ secrets.RENDER_SERVICE_ID }}
                  api-key: ${{ secrets.RENDER_API_KEY }}
